/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SessionSetupRouteImport } from './routes/session/setup'
import { Route as SessionCompleteRouteImport } from './routes/session/complete'
import { Route as SessionActiveRouteImport } from './routes/session/active'
import { Route as DashboardVaultRouteImport } from './routes/dashboard/vault'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSearchRouteImport } from './routes/dashboard/search'
import { Route as DashboardRevisionRouteImport } from './routes/dashboard/revision'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardNotesRouteImport } from './routes/dashboard/notes'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubjectsRouteImport } from './routes/admin/subjects'
import { Route as AdminSpamRouteImport } from './routes/admin/spam'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSearchRouteImport } from './routes/admin/search'
import { Route as AdminRevisionsRouteImport } from './routes/admin/revisions'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLearningRouteImport } from './routes/admin/learning'
import { Route as AdminFilesRouteImport } from './routes/admin/files'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SessionSetupRoute = SessionSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => SessionRoute,
} as any)
const SessionCompleteRoute = SessionCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SessionRoute,
} as any)
const SessionActiveRoute = SessionActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => SessionRoute,
} as any)
const DashboardVaultRoute = DashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevisionRoute = DashboardRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpamRoute = AdminSpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevisionsRoute = AdminRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearningRoute = AdminLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/session': typeof SessionRouteWithChildren
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/vault': typeof VaultRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revisions': typeof AdminRevisionsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spam': typeof AdminSpamRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/revision': typeof DashboardRevisionRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/session/active': typeof SessionActiveRoute
  '/session/complete': typeof SessionCompleteRoute
  '/session/setup': typeof SessionSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/session': typeof SessionRouteWithChildren
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/vault': typeof VaultRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revisions': typeof AdminRevisionsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spam': typeof AdminSpamRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/revision': typeof DashboardRevisionRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/session/active': typeof SessionActiveRoute
  '/session/complete': typeof SessionCompleteRoute
  '/session/setup': typeof SessionSetupRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/session': typeof SessionRouteWithChildren
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/vault': typeof VaultRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/files': typeof AdminFilesRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revisions': typeof AdminRevisionsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/spam': typeof AdminSpamRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/revision': typeof DashboardRevisionRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/session/active': typeof SessionActiveRoute
  '/session/complete': typeof SessionCompleteRoute
  '/session/setup': typeof SessionSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/features'
    | '/login'
    | '/services'
    | '/session'
    | '/signup'
    | '/testimonials'
    | '/vault'
    | '/admin/feedback'
    | '/admin/files'
    | '/admin/learning'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/revisions'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/spam'
    | '/admin/subjects'
    | '/admin/users'
    | '/dashboard/notes'
    | '/dashboard/notifications'
    | '/dashboard/revision'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/vault'
    | '/session/active'
    | '/session/complete'
    | '/session/setup'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/services'
    | '/session'
    | '/signup'
    | '/testimonials'
    | '/vault'
    | '/admin/feedback'
    | '/admin/files'
    | '/admin/learning'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/revisions'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/spam'
    | '/admin/subjects'
    | '/admin/users'
    | '/dashboard/notes'
    | '/dashboard/notifications'
    | '/dashboard/revision'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/vault'
    | '/session/active'
    | '/session/complete'
    | '/session/setup'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/features'
    | '/login'
    | '/services'
    | '/session'
    | '/signup'
    | '/testimonials'
    | '/vault'
    | '/admin/feedback'
    | '/admin/files'
    | '/admin/learning'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/revisions'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/spam'
    | '/admin/subjects'
    | '/admin/users'
    | '/dashboard/notes'
    | '/dashboard/notifications'
    | '/dashboard/revision'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/vault'
    | '/session/active'
    | '/session/complete'
    | '/session/setup'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SessionRoute: typeof SessionRouteWithChildren
  SignupRoute: typeof SignupRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/session/setup': {
      id: '/session/setup'
      path: '/setup'
      fullPath: '/session/setup'
      preLoaderRoute: typeof SessionSetupRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/complete': {
      id: '/session/complete'
      path: '/complete'
      fullPath: '/session/complete'
      preLoaderRoute: typeof SessionCompleteRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/active': {
      id: '/session/active'
      path: '/active'
      fullPath: '/session/active'
      preLoaderRoute: typeof SessionActiveRouteImport
      parentRoute: typeof SessionRoute
    }
    '/dashboard/vault': {
      id: '/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof DashboardVaultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revision': {
      id: '/dashboard/revision'
      path: '/revision'
      fullPath: '/dashboard/revision'
      preLoaderRoute: typeof DashboardRevisionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spam': {
      id: '/admin/spam'
      path: '/spam'
      fullPath: '/admin/spam'
      preLoaderRoute: typeof AdminSpamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revisions': {
      id: '/admin/revisions'
      path: '/revisions'
      fullPath: '/admin/revisions'
      preLoaderRoute: typeof AdminRevisionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learning': {
      id: '/admin/learning'
      path: '/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AdminLearningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/files': {
      id: '/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminLearningRoute: typeof AdminLearningRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRevisionsRoute: typeof AdminRevisionsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpamRoute: typeof AdminSpamRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminLearningRoute: AdminLearningRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRevisionsRoute: AdminRevisionsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpamRoute: AdminSpamRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardRevisionRoute: typeof DashboardRevisionRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVaultRoute: typeof DashboardVaultRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardRevisionRoute: DashboardRevisionRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVaultRoute: DashboardVaultRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SessionRouteChildren {
  SessionActiveRoute: typeof SessionActiveRoute
  SessionCompleteRoute: typeof SessionCompleteRoute
  SessionSetupRoute: typeof SessionSetupRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionActiveRoute: SessionActiveRoute,
  SessionCompleteRoute: SessionCompleteRoute,
  SessionSetupRoute: SessionSetupRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SessionRoute: SessionRouteWithChildren,
  SignupRoute: SignupRoute,
  TestimonialsRoute: TestimonialsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
