export const appRoutes = {
  home: "/",
  login: "/login",
  signup: "/signup",
  dashboard: "/dashboard",
  dashboardUsers: "/dashboard/users",
  dashboardSettings: "/dashboard/settings",
  vault: "/dashboard/vault",
  notes: "/dashboard/notes",
  smartSearch: "/dashboard/search",
  revision: "/dashboard/revision",
  notification: "/dashboard/notifications",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminLearning: "/admin/learning",
  adminRevisions: "/admin/revisions",
  adminFiles: "/admin/files",
  adminSearch: "/admin/search",
  adminSpam: "/admin/spam",
  adminSubjects: "/admin/subjects",
  adminNotifications: "/admin/notifications",
  adminFeedback: "/admin/feedback",
  adminLogs: "/admin/logs",
  adminSettings: "/admin/settings",
} as const;
